default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ExpenseTracker5000.credentials[:db_username] %>
  password: <%= ExpenseTracker5000.credentials[:db_password] %>
  host: <%= ExpenseTracker5000.credentials[:db_host] %>
  port: <%= ExpenseTracker5000.credentials[:db_port] %>

development:
  <<: *default
  database: expense_tracker_5000_development

test:
  <<: *default
  database: expense_tracker_5000_test

production:
  <<: *default
  database: expense_tracker_5000_production
